/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-07-03 07:54:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


java.sql.Connection conn=null;
java.sql.Statement stmt=null;
java.sql.ResultSet rs=null;

String driver="oracle.jdbc.driver.OracleDriver";
String url="jdbc:oracle:thin:@localhost:1521:xe";
String user="scott";
String password="tiger";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/emp/../template/menu.jspf", Long.valueOf(1593762842539L));
    _jspx_dependants.put("/emp/../template/footer.jspf", Long.valueOf(1593738573946L));
    _jspx_dependants.put("/emp/../template/header.jspf", Long.valueOf(1593762496528L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Emp List Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"lightgray\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<table width=\"1024\" align=\"center\" bgcolor=\"white\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t");

			Object obj =session.getAttribute("name");
			if(obj!=null){
			String loginName =(String)obj;
			out.print(loginName+"님 로그인중...");
			}
	
		
      out.write("\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<img src=\"/web05/img/logo.png\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t<td bgcolor=\"gray\" align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"/web05/index.jsp\" style=\"color:white;\">[Home]</a>\r\n");
      out.write("\t\t\t<a href=\"/web05/emp/list.jsp\" style=\"color:white;\">[E M P]</a>\r\n");
      out.write("\t\t\t<a href=\"/web05/dept/list.jsp\" style=\"color:white;\">[DEPT]</a>\r\n");
      out.write("\t\t\t");

				if(obj==null){
			
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/web05/login/form.jsp\" style=\"color:white;\">[Login]</a>\r\n");
      out.write("\t\t\t");

				}else{
			
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/web05/login/logout.jsp\" style=\"color:white;\">[Logout]</a>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t<!--content start  -->");
      out.write("\r\n");
      out.write("\t<h1>List Page</h1>\r\n");
      out.write("\t<p align=\"center\">\r\n");
      out.write("\t<a href=\"add.jsp\">[입 력]</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<table width=\"95%\" border=\"1\" cellspacing=\"0\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>사번</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>날짜</th>\r\n");
      out.write("\t\t\t<th>금액</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
 
			int tot=0;  // select count(*) from emp01;
			int p=1;
			String param=request.getParameter("page");
			if(param!=null){
				p=Integer.parseInt(param);
			}
			int startNum=1+((p-1)*10);
			int endNum=10+((p-1)*10);
		
			String sql="select * from (select rownum as rn,sabun,name,nalja,pay from";
			sql+="(select * from emp01 order by sabun desc)) where rn between "+startNum+" and "+endNum;

			Class.forName(driver);
			
			try{
				conn=DriverManager.getConnection(url,user,password);
				stmt=conn.createStatement();
				rs=stmt.executeQuery("select count(*) from emp01");
				if(rs.next()){
					tot=rs.getInt(1);
				}
				stmt=conn.createStatement();
				rs=stmt.executeQuery(sql);
				while(rs.next()){
					
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><a href=\"detail.jsp?idx=");
      out.print(rs.getInt("sabun"));
      out.write('"');
      out.write('>');
      out.print(rs.getInt("sabun") );
      out.write("</a></td>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs.getString("name") );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs.getDate("nalja") );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(rs.getInt("pay") );
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

				}
			}finally{
				if(rs!=null)rs.close();
				if(stmt!=null)stmt.close();
				if(conn!=null)conn.close();
			}
		
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<!--  -->\r\n");
      out.write("\t");
 
		//int tot=151;
		//if(tot%10==0)tot=tot/10;
		//else tot=tot/10+1;
		
		//p=1~10	-1/10 =0	+1*10  -> limit=10;
		//p=11~20	-1/10 =1	+1*10  -> limit=20;
		//p=21~30	-1/10 =2	+1*10  -> limit=30;
		//p=31~40	-1/10 =3	+1*10  -> limit=limit;
		
		int lang=10;
		
		
		int limit=(tot-1)/10+1;
		int start=((p-1)/lang)*lang;
		int end =start+lang;
		if(end>limit)end=limit;

		if(p>=lang+1){
			out.print("<a href=list.jsp?page="+(start)+">[이 전]</a>");
		}

		for(int i=start;i<end;i++){
	
      out.write("\r\n");
      out.write("\t\t<a href=\"list.jsp?page=");
      out.print(i+1);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(i+1 );
      out.write("]</a>\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
		}
		if(end<limit){
			out.print("<a href=list.jsp?page="+(end+1)+">[다 음]</a>");
		}	
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t<!--content end  -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td bgcolor=\"gray\" align=\"center\">\r\n");
      out.write("\t\t\t<font color=\"white\">\r\n");
      out.write("\t\t\t비트캠프 서울시 서초구 강남대로 459 (서초동, 백암빌딩)<br>\r\n");
      out.write("\t\t\t｜ 사업자등록번호 : 214-85-24928<br>\r\n");
      out.write("\t\t\tCopyright (c) 비트캠프 All rights reserved.<br>\r\n");
      out.write("\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
