/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-07-07 03:57:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.bit.emp.EmpDto;
import com.bit.emp.EmpCRUD;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <table width=\"1024\" align=\"center\">\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td>\r\n");
      out.write("            <img alt=\"\" src=\"/web08/img/logo.png\">\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td align=\"center\" bgcolor=\"#cccccc\">\r\n");
      out.write("            <a href=\"../index.jsp\">[HOME]</a>\r\n");
      out.write("            <a href=\"./emp/lisg.jsp\">[E M P]</a>\r\n");
      out.write("            <a href=\"../dept/list.jsp\">[DEPT]</a>\r\n");
      out.write("            <a href=\"../login/form.jsp\">[LOGIN]</a>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td>\r\n");
      out.write("            <!-- content start -->\r\n");
      out.write("            <center>\r\n");
      out.write("            <h1>상세 페이지</h1>\r\n");
      out.write("            ");
      com.bit.emp.EmpDto bean = null;
      bean = (com.bit.emp.EmpDto) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (bean == null){
        bean = new com.bit.emp.EmpDto();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("bean"), "sabun", request.getParameter("sabun"), request, "sabun", false);
      out.write("  <!-- bean.setSabun(Integer.parseInt(request.getParameter(\"sabun\"))) -->\r\n");
      out.write("            ");

            	bean= EmpCRUD.detail(bean.getSabun());
            
      out.write("\r\n");
      out.write("            \t<table width=\"800\">\r\n");
      out.write("            \t\t<tr>\r\n");
      out.write("            \t\t\t<td width=\"300\" bgcolor=\"#cccccc\">사번</td>\r\n");
      out.write("            \t\t\t<td>");
      out.print(bean.getSabun() );
      out.write("</td>\r\n");
      out.write("            \t\t</tr>\r\n");
      out.write("            \t\t<tr>\r\n");
      out.write("            \t\t\t<td width=\"300\" bgcolor=\"#cccccc\">이름</td>\r\n");
      out.write("            \t\t\t<td>");
      out.print(bean.getName() );
      out.write("</td>\r\n");
      out.write("            \t\t</tr>\r\n");
      out.write("            \t\t<tr>\r\n");
      out.write("            \t\t\t<td width=\"300\" bgcolor=\"#cccccc\">날짜</td>\r\n");
      out.write("            \t\t\t<td>");
      out.print(bean.getNalja() );
      out.write("</td>\r\n");
      out.write("            \t\t</tr>\r\n");
      out.write("            \t\t<tr>\r\n");
      out.write("            \t\t\t<td>금액</td>\r\n");
      out.write("            \t\t\t<td>");
      out.print(bean.getPay() );
      out.write("</td>\r\n");
      out.write("            \t\t</tr>\r\n");
      out.write("            \t\t<tr>\r\n");
      out.write("            \t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("            \t\t\t\t<a href=\"edit.jsp?sabun=");
      out.print(bean.getSabun());
      out.write("&name=");
      out.print(bean.getName());
      out.write("&pay=");
      out.print(bean.getPay());
      out.write("\">[수 정]</a>\r\n");
      out.write("            \t\t\t\t<a href=\"delete.jsp\">[삭 제]</a>\r\n");
      out.write("            \t\t\t</td>\r\n");
      out.write("            \t\t</tr>\r\n");
      out.write("            \t</table>\r\n");
      out.write("            </center>\r\n");
      out.write("            <!-- content end -->\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("         <td align=\"center\" bgcolor=\"#cccccc\">\r\n");
      out.write("            비트캠프 서울시 서초구 강남대로 459 (서초동, 백암빌딩)<br>\r\n");
      out.write("            (주)비트컴퓨터 서초본원 대표이사 : 조현정<br>\r\n");
      out.write("            Copyright (c) 비트캠프 All rights reserved.<br>\r\n");
      out.write("         </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
